from models.lesson import Lesson

# static catalog for phase 1-6 — replaced by a db-backed repo later.
# every lesson that binds to a gesture id in /vision/gestures/samples.py will
# render the live mirror; the rest stay as card-only content for now.
_SEED: list[Lesson] = [
    Lesson(
        id="hello",
        title="hello",
        description="wave an open palm beside your temple, then move it outward.",
        difficulty="starter",
        tags=["greetings", "daily"],
        gesture_ids=["hello"],
        scenario_tag="daily",
    ),
    Lesson(
        id="thank-you",
        title="thank you",
        description="flat hand touches chin and moves forward, like blowing a kiss.",
        difficulty="starter",
        tags=["manners", "daily"],
        gesture_ids=["thank_you"],
        scenario_tag="daily",
    ),
    Lesson(
        id="please",
        title="please",
        description="soft open hand circling at the chest — gentle and polite.",
        difficulty="starter",
        tags=["manners", "daily"],
        gesture_ids=["please"],
        scenario_tag="daily",
    ),
    Lesson(
        id="sorry",
        title="sorry",
        description="closed fist on the chest — small circle, eyes soft.",
        difficulty="starter",
        tags=["manners", "feelings"],
        gesture_ids=["sorry"],
        scenario_tag="daily",
    ),
    Lesson(
        id="water",
        title="water",
        description="form a 'w' with three fingers; tap it against your chin.",
        difficulty="starter",
        tags=["mealtime", "needs"],
        gesture_ids=["water"],
        scenario_tag="daily",
    ),
    Lesson(
        id="food",
        title="food",
        description="pinch all fingertips together, tap toward the mouth.",
        difficulty="starter",
        tags=["mealtime", "needs"],
        gesture_ids=["food"],
        scenario_tag="mealtime",
    ),
    Lesson(
        id="help",
        title="help",
        description="thumb-up fist lifted on the other palm, raised together.",
        difficulty="growing",
        tags=["safety", "needs"],
        gesture_ids=["help"],
        scenario_tag="safety",
    ),
    Lesson(
        id="stop",
        title="stop",
        description="flat palm facing out, fingers straight up — held still.",
        difficulty="starter",
        tags=["safety", "daily"],
        gesture_ids=["stop"],
        scenario_tag="safety",
    ),
    Lesson(
        id="yes",
        title="yes",
        description="closed fist, gentle nodding motion.",
        difficulty="starter",
        tags=["daily", "communication"],
        gesture_ids=["yes"],
        scenario_tag="daily",
    ),
    Lesson(
        id="no",
        title="no",
        description="index and middle extended, snap down to meet the thumb.",
        difficulty="starter",
        tags=["daily", "communication"],
        gesture_ids=["no"],
        scenario_tag="daily",
    ),
    Lesson(
        id="bathroom",
        title="bathroom",
        description="fist with thumb peeking between index and middle — small shake.",
        difficulty="growing",
        tags=["needs", "daily"],
        gesture_ids=["bathroom"],
        scenario_tag="home",
    ),
    Lesson(
        id="pain",
        title="pain",
        description="index finger points firmly toward where it hurts.",
        difficulty="growing",
        tags=["safety", "feelings"],
        gesture_ids=["pain"],
        scenario_tag="safety",
    ),
    Lesson(
        id="tired",
        title="tired",
        description="fingers droop at the second knuckle — loose and heavy.",
        difficulty="growing",
        tags=["feelings", "daily"],
        gesture_ids=["tired"],
        scenario_tag="home",
    ),
    Lesson(
        id="play",
        title="play",
        description="'y' hand — thumb and pinky out, middle fingers curled; gentle shake.",
        difficulty="growing",
        tags=["family", "fun"],
        gesture_ids=["play"],
        scenario_tag="family",
    ),
    Lesson(
        id="sleep",
        title="sleep",
        description="soft fingers drift down the face, palm turning inward.",
        difficulty="growing",
        tags=["home", "daily"],
        gesture_ids=["sleep"],
        scenario_tag="home",
    ),
    # phase 8 expansion
    Lesson(
        id="drink",
        title="drink",
        description="c-shape hand tilted back — like holding a cup to your lips.",
        difficulty="starter",
        tags=["mealtime", "needs"],
        gesture_ids=["drink"],
        scenario_tag="mealtime",
    ),
    Lesson(
        id="eat",
        title="eat",
        description="relaxed flat hand, fingertips tapping toward the mouth.",
        difficulty="starter",
        tags=["mealtime", "needs"],
        gesture_ids=["eat"],
        scenario_tag="mealtime",
    ),
    Lesson(
        id="friend",
        title="friend",
        description="hook index fingers together, swap which is on top.",
        difficulty="growing",
        tags=["people", "family"],
        gesture_ids=["friend"],
        scenario_tag="family",
    ),
    Lesson(
        id="family",
        title="family",
        description="pinch hand sweeping in a circle — everyone together.",
        difficulty="growing",
        tags=["people", "family"],
        gesture_ids=["family"],
        scenario_tag="family",
    ),
    Lesson(
        id="doctor",
        title="doctor",
        description="'d' hand tapped on the opposite wrist — taking a pulse.",
        difficulty="growing",
        tags=["safety", "people"],
        gesture_ids=["doctor"],
        scenario_tag="safety",
    ),
    Lesson(
        id="school",
        title="school",
        description="flat palms clapping twice — calling attention.",
        difficulty="growing",
        tags=["places", "daily"],
        gesture_ids=["school"],
        scenario_tag="daily",
    ),
    Lesson(
        id="home",
        title="home",
        description="pinched fingertips from cheek to jaw — where you eat and sleep.",
        difficulty="starter",
        tags=["places", "daily"],
        gesture_ids=["home"],
        scenario_tag="home",
    ),
    Lesson(
        id="wait",
        title="wait",
        description="open hands, fingers half-curled, held up with a small wiggle.",
        difficulty="growing",
        tags=["daily", "communication"],
        gesture_ids=["wait"],
        scenario_tag="daily",
    ),
    Lesson(
        id="come",
        title="come",
        description="index finger beckoning toward you — palm up.",
        difficulty="growing",
        tags=["daily", "communication"],
        gesture_ids=["come"],
        scenario_tag="daily",
    ),
    Lesson(
        id="go",
        title="go",
        description="index finger pointing outward, thumb up — off you go.",
        difficulty="growing",
        tags=["daily", "communication"],
        gesture_ids=["go"],
        scenario_tag="daily",
    ),
    Lesson(
        id="more",
        title="more",
        description="pinched fingertips tapped together twice.",
        difficulty="starter",
        tags=["mealtime", "requests"],
        gesture_ids=["more"],
        scenario_tag="mealtime",
    ),
    Lesson(
        id="finished",
        title="finished",
        description="open palms flipped outward — all done.",
        difficulty="starter",
        tags=["daily", "communication"],
        gesture_ids=["finished"],
        scenario_tag="daily",
    ),
    # alphabet primer cards — one per letter, surfaced in the lessons feed so
    # a browsing learner can discover the alphabet section without typing the
    # url. each lesson binds to its `letter_*` gesture so the live mirror
    # works straight from the lesson card.
    Lesson(id="alphabet-a", title="letter a", description="closed fist with the thumb resting along the side — keep it flat, not tucked.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_a"], scenario_tag="alphabet"),
    Lesson(id="alphabet-b", title="letter b", description="four fingers up flat; thumb crosses the palm to meet the pinky base.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_b"], scenario_tag="alphabet"),
    Lesson(id="alphabet-c", title="letter c", description="fingers and thumb curve to form a relaxed letter c.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_c"], scenario_tag="alphabet"),
    Lesson(id="alphabet-d", title="letter d", description="index up; the other three curl down so their tips touch the thumb pad.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_d"], scenario_tag="alphabet"),
    Lesson(id="alphabet-e", title="letter e", description="fingers fold flat; thumb tucks horizontally across the fingertips.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_e"], scenario_tag="alphabet"),
    Lesson(id="alphabet-f", title="letter f", description="thumb and index pinch into an 'ok'; middle, ring, and pinky stay tall.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_f"], scenario_tag="alphabet"),
    Lesson(id="alphabet-g", title="letter g", description="fist on its side; thumb and index point forward in parallel.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_g"], scenario_tag="alphabet"),
    Lesson(id="alphabet-h", title="letter h", description="index and middle stacked, pointing sideways; the rest fold down.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_h"], scenario_tag="alphabet"),
    Lesson(id="alphabet-i", title="letter i", description="make a fist with the thumb across, then lift only the pinky.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_i"], scenario_tag="alphabet"),
    Lesson(id="alphabet-j", title="letter j", description="start in 'i'; trace a small j hook in the air with the pinky.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_j"], scenario_tag="alphabet"),
    Lesson(id="alphabet-k", title="letter k", description="index up, middle angled out; thumb rests in the v between them.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_k"], scenario_tag="alphabet"),
    Lesson(id="alphabet-l", title="letter l", description="thumb out sideways and index straight up — a clean 90° angle.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_l"], scenario_tag="alphabet"),
    Lesson(id="alphabet-m", title="letter m", description="fold the first three fingers down over the thumb; pinky stays curled.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_m"], scenario_tag="alphabet"),
    Lesson(id="alphabet-n", title="letter n", description="fold index and middle over the thumb; ring and pinky stay tight.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_n"], scenario_tag="alphabet"),
    Lesson(id="alphabet-o", title="letter o", description="all fingertips touch the thumb pad to form a round 'o'.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_o"], scenario_tag="alphabet"),
    Lesson(id="alphabet-p", title="letter p", description="make a 'k' shape, then tip the whole hand so the index aims at the floor.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_p"], scenario_tag="alphabet"),
    Lesson(id="alphabet-q", title="letter q", description="make a 'g', then tip the knuckles forward so it points downward.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_q"], scenario_tag="alphabet"),
    Lesson(id="alphabet-r", title="letter r", description="twist the index over the middle; the rest curl with thumb across.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_r"], scenario_tag="alphabet"),
    Lesson(id="alphabet-s", title="letter s", description="tight fist with the thumb wrapped over the front of the fingers.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_s"], scenario_tag="alphabet"),
    Lesson(id="alphabet-t", title="letter t", description="fold the fingers; let the thumb peek between index and middle knuckles.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_t"], scenario_tag="alphabet"),
    Lesson(id="alphabet-u", title="letter u", description="two fingers straight up and touching; ring and pinky curl over the thumb.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_u"], scenario_tag="alphabet"),
    Lesson(id="alphabet-v", title="letter v", description="index and middle up but split apart; the others fold tight.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_v"], scenario_tag="alphabet"),
    Lesson(id="alphabet-w", title="letter w", description="three fingers up like a fan; thumb pins the pinky across the palm.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_w"], scenario_tag="alphabet"),
    Lesson(id="alphabet-x", title="letter x", description="fist with the index out and bent at the middle knuckle — a small hook.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_x"], scenario_tag="alphabet"),
    Lesson(id="alphabet-y", title="letter y", description="extend thumb and pinky; the middle three fingers fold to the palm.", difficulty="starter", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_y"], scenario_tag="alphabet"),
    Lesson(id="alphabet-z", title="letter z", description="point with the index and trace a clean z — three quick strokes.", difficulty="growing", tags=["alphabet", "fingerspelling"], gesture_ids=["letter_z"], scenario_tag="alphabet"),
]


class LessonService:
    def list_lessons(self) -> list[Lesson]:
        return list(_SEED)


lesson_service = LessonService()
